# Customized values for appdeploy chart
# https://github.com/bitsofinfo/appdeploy

app:
  environment: "stage"
  context: "stage-qa"

containerPorts:
  - name: nginx80
    port: 80
    service: true
    ingress: true
    tls: false

healthcheck:
  liveness:
    containerPort: 80
    path: /
    scheme: HTTP
  readiness:
    containerPort: 80
    path: /
    scheme: HTTP

hooks:
  default:
    postInstallUpgrade:
      validator:
        useIngressHost: false
        checksConfig:
          - name: "/"
            path: /
            method: GET
            timeout: 5
            retries: 15
            tags: ["80"]
        slackConfig:
          postDeploy:
            # INTENTIONALLY public for this example!
            webhook_url: "https://hooks.slack.com/services/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"
    postDelete:
      validator:
        useIngressHost: false
        slackConfig:
          postDelete:
            # INTENTIONALLY public for this example!
            webhook_url: "https://hooks.slack.com/services/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"


ingress:
  metadata:
    annotations:
      - name: "kubernetes.io/ingress.class"
        value: "traefik"
    dns:
      fqdnSuffix: ".local"
    labels:
      - name: "bitsofinfo-ingress"
        value: "yes"
