chartConfigs:

  # Customized values for appdeploy chart
  # https://github.com/bitsofinfo/appdeploy
  # values here will override/merge w/ those
  # specified anywhere above
  appdeploy:
    chartValues:
      values:
        image:
          repository: "bitsofinfo/catapp"

        # here is an example (has no actual effect on running app)
        # of referencing "helmfile" state value data defined
        # in examples/values/customized-cluster.yaml
        env:
          INGRESS_CONTROLLER_URL:
            value: "{{.helmfile.targetCluster.ingressControllers.default.url}}"
