chartConfigs:

  # Customized values for appdeploy chart
  # https://github.com/bitsofinfo/appdeploy
  # values here will override/merge w/ those
  # specified anywhere above
  appdeploy:
    chartValues:
      baseValues:
        - testapps
        - hogapp
        - hogapp/{{.environmentName}}
        - hogapp/{{.environmentName}}/{{.contextName}}

      values:
        image:
          repository: "bitsofinfo/hogapp"

        containerPorts:
          - name: nginx80
            port: 80
            service: true
            ingress: true
            tls: false
          - name: nginx443
            port: 443
            service: true
            ingress: true
            tls: true

        # here is an example (has no actual effect on running app)
        # of referencing "helmfile" state value data defined
        # in examples/values/customized-chartconfigs.yaml
        env:
          INGRESS_CONTROLLER_URL:
            value: "{{.helmfile.targetCluster.ingressControllers.default.url}}"
