# These customize the defaults in helmfile-deploy/values/000-globals.yaml
# and will affect all environments (unless overridden)
# @see helmfile-deploy/values/000-globals.yaml for details

chartConfigs:

  appconduits:
    chartValues:
      baseValues:
        - testapps

  appdeploy:
    chartValues:
      baseValues:
        - testapps
