# Customized values for appconduits chart
# https://github.com/bitsofinfo/appconduits

hooks:
  postInstallUpgrade:
    # INTENTIONALLY PUBLIC FOR THIS EXAMPLE!
    webhook_url: https://hooks.slack.com/services/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
